# print('Welcome to the Grade Sorter App \n')
# grade1 = int(input('What is your first grade(0-100):'))
# grade2 = int(input('What is your second grade(0-100):'))
# grade3 = int(input('What is your third grade(0-100):'))
# grade4 = int(input('What is your fourth grade(0-100):'))
# grade_list = [grade1, grade2, grade3, grade4]
# print('\nYour Grades are:', grade_list)
# grade_list_sorted = sorted(grade_list, reverse= True)
# print('\nYour Grades from highest to lowest are:', grade_list_sorted)
# print('\nThe Lowest 2 grades will now be dropped.')
# print('Removed Grade:',grade_list_sorted.pop())
# print('Removed Grade:',grade_list_sorted.pop())
# print('\nYour Remaining Grades are:', grade_list_sorted)
# print('Nice Work!  Your highest grade is a',grade_list_sorted[0])

print('Welcome to the Grade Sorter App \n')
grades = []
grade = int(input('What is your first grade(0-100):'))
grades.append(grade)
grade = int(input('What is your second grade(0-100):'))
grades.append(grade)
grade = int(input('What is your third grade(0-100):'))
grades.append(grade)
grade = int(input('What is your fourth grade(0-100):'))
grades.append(grade)
print('\nYour Grades are:', grades)
grades.sort(reverse= True)
print('\nYour Grades from highest to lowest are:', grades)
print('\nThe Lowest 2 grades will now be dropped.')
print('Removed Grade:',grades.pop())
print('Removed Grade:',grades.pop())
print('\nYour Remaining Grades are:', grades)
print('Nice Work!  Your highest grade is a '+ str(grades[0]) + '.')
