print('Welcome to the Basketball Roster Program\n')
team =[]
player = input('Who is your point gaurd:').title()
team.append(player)
player = input('Who is your shooting gaurd:').title()
team.append(player)
player = input('Who is your small forward:').title()
team.append(player)
player = input('Who is your power forward:').title()
team.append(player)
player = input('Who is your small center:').title()
team.append(player)

print('\t\tYour starting 5 for the upcoming basketball season')
print(f'\t\t\t\tPoint Gaurd:\t\t{team[0]}')
print(f'\t\t\t\tshooting Gaurd:\t\t{team[1]}')
print(f'\t\t\t\tSmall Forward:\t\t{team[2]}')
print(f'\t\t\t\tPower Forward:\t\t{team[3]}')
print(f'\t\t\t\tCenter:\t\t\t\t{team[4]}')
injured = team.pop(2)
print(f'Oh no, {injured} is injured.')
print(f'Your roster only has {len(team)} players.')
player = input(f'Who will take {injured}\'s spot:').title()
team.insert(2, player)
print('\t\tYour starting 5 for the upcoming basketball season')
print(f'\t\t\t\tPoint Gaurd:\t\t{team[0]}')
print(f'\t\t\t\tshooting Gaurd:\t\t{team[1]}')
print(f'\t\t\t\tSmall Forward:\t\t{team[2]}')
print(f'\t\t\t\tPower Forward:\t\t{team[3]}')
print(f'\t\t\t\tCenter:\t\t\t\t{team[4]}')
print(f'Good Luck {player} you will do great!')
print(f'Your roster now has {len(team)} players.')
