print('Welcome to the Multiplication/Exponent Table App')
name = input('Hello, what is your name:').title().strip()
number = float(input('What number would you like to work with:'))
print(f'\nMultiplication Table for {number}\n')
print(f'\t1.0 * {number} = ' ,1.0 * number)
print(f'\t2.0 * {number} = ' ,2.0 * number)
print(f'\t3.0 * {number} = ' ,3.0 * number)
print(f'\t4.0 * {number} = ' ,4.0 * number)
print(f'\t5.0 * {number} = ' ,5.0 * number)
print(f'\t6.0 * {number} = ' ,6.0 * number)
print(f'\t7.0 * {number} = ' ,7.0 * number)
print(f'\t8.0 * {number} = ' ,8.0 * number)
print(f'\t9.0 * {number} = ' ,9.0 * number)
print('\n')
print(f'Exponent Table for {number}\n')
print(f'\t{number} ** 1 = ',number**1)
print(f'\t{number} ** 2 = ',number**2)
print(f'\t{number} ** 3 = ',number**3)
print(f'\t{number} ** 4 = ',number**4)
print(f'\t{number} ** 5 = ',number**5)
print(f'\t{number} ** 6 = ',number**6)
print(f'\t{number} ** 7 = ',number**7)
print(f'\t{number} ** 8 = ',number**8)
print(f'\t{number} ** 9 = ',number**9)
print('\n')
print(f'{name} Math is cool!')
print(f'\t{name} Math is cool!'.lower())
print(f'\t\t{name} Math is cool!'.title())
print(f'\t\t\t{name} Math is cool!'.upper())