print('Welcome to the Multipliacation/Exponent Table App:')
name = input('Hello, What is your name:')
number = float(input('What would you like to work with:'))
print(f'Multiplication Table For {number}:')
print('\t')